# Generated by Django 4.0.10 on 2024-07-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_indicatorsubcategory_adddatadesc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('category', models.IntegerField()),
                ('subCategory', models.IntegerField()),
                ('dateStart', models.DateField(blank=True, null=True)),
                ('dateEnd', models.DateField(blank=True, null=True)),
                ('accepted', models.DecimalField(decimal_places=2, max_digits=10)),
                ('name', models.CharField(max_length=100)),
                ('graphCategory', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('color', models.CharField(blank=True, max_length=100)),
                ('year', models.DecimalField(decimal_places=2, max_digits=10)),
                ('district', models.DecimalField(decimal_places=2, max_digits=10)),
                ('state', models.DecimalField(decimal_places=2, max_digits=10)),
                ('isVerified', models.BooleanField()),
            ],
        ),
    ]
